const writers = [
    {
        name: 'William Shakespeare',
        born: ' 23rd April 1564',
        totalWork: 192,
        bestWorks: ['Hamlet', 'Macbeth', 'Othello'],
        image: './images/fake1.jpg',
        quote: `Life’s but a walking shadow, a poor player
    That struts and frets his hour upon the stage,
    And then is heard no more. It is a tale
    Told by an idiot, full of sound and fury,
    Signifying nothing.`
    },
    {
        name: 'Jonathan Swift ',
        born: ' 30 November 1667',
        totalWork: 176,
        bestWorks: ['A Tale of a Tub (1704)', 'An Argument Against Abolishing Christianity (1712)', "Gulliver's Travels (1726)", " and A Modest Proposal (1729)"],
        image: './images/fake2.jpg',
        quote: `Satire is a sort of glass, wherein beholders do generally discover everybody's face but their own.`
    },
    {
        name: 'Samuel Johnson ',
        born: ' 18 September 1709',
        totalWork: 45,
        bestWorks: ['A Dictionary of the English Language '],
        image: './images/fake3.jpg',
        quote: `Mankind have a great aversion to intellectual labor; but even supposing knowledge to be easily attainable, more people would be content to be ignorant than would take even a little trouble to acquire it.`
    },
    {
        name: 'Johann Wolfgang von Goethe  ',
        born: ' 28 August 1749 ',
        totalWork: 13,
        bestWorks: ['e Faust', "Wilhelm Meister’s Apprenticeship ", 'Elective Affinities'],
        image: './images/fake4.jpg',
        quote: `Knowing is not enough; we must apply. Willing is not enough; we must do.`
    },
    {
        name: 'Charles Dickens  ',
        born: '  7 February 1812 ',
        totalWork: 66,
        bestWorks: ['Oliver Twist', 'Great Expectations', 'David Copperfield'],
        image: './images/fake5.jpg',
        quote: `Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.`
    },
    {
        name: 'Leo Tolstoy   ',
        born: ' 1828 ',
        totalWork: 76,
        bestWorks: ['War and Peace', 'Anna Karenina'],
        image: './images/fake6.jpg',
        quote: `The hero of my tale, whom I love with all the power of my soul, whom I have tried to portray in all his beauty, who has been, is, and will be beautiful, is Truth.`
    },
    {
        name: 'George Eliot   ',
        born: ' 1858',
        totalWork: 53,
        bestWorks: ["The Mill on the Floss (1860)", "Silas Marner (1861)", "Middlemarch (1871–72)"],
        image: './images/fake7.jpg',
        quote: `It will never rain roses: when we want to have more roses, we must plant more roses.`
    },
    {
        name: 'Mark Twain   ',
        born: ' November 30, 1835 ',
        totalWork: 144,
        bestWorks: ['The Adventures of Tom Sawyer', 'Adventures of Huckleberry Fin'],
        image: './images/fake8.jpg',
        quote: `Lies, damned lies, and statistics`
    },
    {
        name: 'Oscar Wilde   ',
        born: ' 16 October 1854 ',
        totalWork: 25,
        bestWorks: [' The Importance of Being Earnest (1895)'],
        image: './images/fake9.jpg',
        quote: `To get back my youth I would do anything  in the world, except take exercise, get up early or be respectable.`
    },
    {
        name: 'Arthur Conan Doyle',
        born: ' 22 May 1859  ',
        totalWork: 94,
        bestWorks: [' A Study in Scarlet'],
        image: './images/fake10.jpg',
        quote: `How often have I said to you that when you have eliminated the impossible, whatever remains, however improbable, must be the truth?`
    }




]
